website/__init__.py
from flask import Flask
from dotenv import load_dotenv
import os
import sys
from os.path import abspath, dirname
sys.path.append(dirname(dirname(abspath(__file__))))
from .db import db


load_dotenv()

app = Flask(__name__)

app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')
app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv("DATABASE_URL")

from .views import views
from .auth import auth

app.register_blueprint(views, url_prefix='/') 
app.register_blueprint(auth, url_prefix='/') 

db.init_app(app)

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, session, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from website.db import db
from sqlalchemy.sql import text

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        query = db.session.execute(text("SELECT * FROM users WHERE email = :email"), {"email": email})
        user = query.fetchone()

        if user:
            if check_password_hash(user.password, password):
                session["user_id"] = user.id
                print(user.id)
                flash('Logged in successfully!', category='success')
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist, create an account.', category='error')

    return render_template("login.html")

@auth.route("/logout")
def logout():
    session.pop("user_id", None) 
    flash('You have been logged out.', category='success')
    return redirect('/login')


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        query = db.session.execute(text("SELECT * FROM users WHERE email = :email"), {"email": email})
        user = query.fetchone()

        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be grater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be grater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords must match', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            hashed_password = generate_password_hash(password1)
            db.session.execute(text("INSERT INTO users (email, first_name, password) VALUES (:email, :first_name, :hashed_password)"), 
                               {"email": email, "first_name": first_name, "hashed_password": hashed_password})
            db.session.commit()
            flash('Account created! ', category='success')
            return redirect(url_for('auth.login'))
        
    return render_template("sign_up.html")

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, session, url_for
from website.db import db
from sqlalchemy.sql import text
import os


views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def home():
    current_user = session.get("user_id")
    if request.method == 'POST':
        entry_text = request.form.get('entry')
        if len(entry_text) < 1:
            flash('Entry is too short!', category='error')
        else:
            db.session.execute(text("INSERT INTO entry (data, user_id) VALUES (:entry_text, :user_id)"), 
                                {"entry_text": entry_text, "user_id": current_user})
            db.session.commit()
            flash('Entry added!', category='success')

    entries_query = db.session.execute(text("SELECT * FROM entry"))
    entries = entries_query.fetchall()

    return render_template("home.html", user=current_user, entries=entries)




@views.route('/delete-entry/<int:entry_id>', methods=['POST'])
def delete_entry(entry_id):

    db.session.execute(text("DELETE FROM entry_notes WHERE id =:entry_id"), {"entry_id": entry_id})
    db.session.execute(text("DELETE FROM entry WHERE id = :entry_id"), {"entry_id": entry_id})
    db.session.commit()

    flash('Entry deleted', category='success')
    return redirect(url_for('views.home'))


@views.route('/entry/<int:entry_id>')
def entry(entry_id):
    entry = db.session.execute(text("SELECT * FROM entry WHERE id = :entry_id"), {"entry_id": entry_id}).fetchone()
    entry_notes = db.session.execute(text("SELECT * FROM entry_notes WHERE entry_id = :entry_id"), {"entry_id": entry_id}).fetchall()
    
    current_user = session.get("user_id")
    uploaded_file = db.session.execute(text("SELECT filename FROM pictures_files WHERE user_id = :current_user ORDER BY id DESC LIMIT 1"), {"current_user": current_user}).scalar()
    
    return render_template("entry.html", entry=entry, entry_notes=entry_notes, entry_id=entry_id, uploaded_file=uploaded_file)


@views.route('/add-note/<int:entry_id>', methods=['POST'])
def add_note(entry_id):
    note_text = request.form.get('note_text')
    current_user = session.get("user_id")


    file = request.files.get('file')
    filename = None

    if file:
        filename = file.filename
        file_path = os.path.join('static', 'css', 'uploads', filename)

        file.save(file_path)


        file_data = file.read()
        db.session.execute(text("INSERT INTO pictures_files (filename, file_data, user_id) VALUES (:filename, :file_data, :user_id)"),
                           {"filename":filename, "file_data":file_data, "user_id":current_user})
        db.session.commit()



    db.session.execute(text("INSERT INTO entry_notes (content, entry_id, user_id) VALUES (:content, :entry_id, :user_id)"), 
                            {"content": note_text, "entry_id": entry_id, "user_id": current_user})
    db.session.commit()
    flash('Note added!', category='success')

        
    return redirect(url_for('views.entry', entry_id=entry_id))


@views.route('/delete-note/<int:note_id>', methods=['POST'])
def delete_note(note_id):
    db.session.execute(text("DELETE FROM entry_notes WHERE id = :note_id"), {"note_id": note_id})
    db.session.commit()

    flash('Note deleted', category='success')
    
    return redirect(request.referrer)




@views.route('/user')
def user():
    user_id = session.get("user_id")

    if user_id:
        first_name = db.session.execute(text("SELECT first_name FROM users WHERE id = :user_id"), {"user_id": user_id}).scalar()

        search_query = request.args.get('search_query', '')

        search_results = db.session.execute(
            text("SELECT * FROM entry WHERE user_id = :user_id AND data ILIKE :search_query"),
            {"user_id": user_id, "search_query": f"%{search_query}%"}).fetchall()

        return render_template('user.html', first_name=first_name, search_results=search_results)

    

website/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous"   
        />
        <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous"
        />
        
        
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Cantata+One&display=swap" rel="stylesheet">
        
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

        <title>{% block title %}Home{% endblock %}</title>

        <style>
            body {
                font-family: 'Cantata One', serif; 
                color: #121610
            }
        </style>
    </head>
    <body class="custom-background">

        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #4e7c5b;">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                    {% if session.user_id %}
                    <a class="nav-item nav-link" id="home" href="/">Home</a>
                    <a class="nav-item nav-link" id="user" href="/user">User</a>
                    <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" id="login" href="/login">Login</a>
                    <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign up</a>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            {% if category == 'error' %}
            <div class="alert alert-danger alert-dismissable fade show", role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% else %}
            <div class="alert alert-success alert-dismissable fade show", role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %} {% endfor %} {% endif %} {% endwith %}

        <div class="container">
        {% block content %}
        {% endblock %}
        </div>

        <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
        type="text/javascript"
        src="{{ url_for('static', filename='index.js') }}"
        ></script>
    </body>
</html>

website/templates/entry.html
{% extends "base.html" %}
{% block title %}Entry{% endblock %}


{% block content %}
<div class="row">
    <div class="col-md-8 offset-md-2">
        <h1 style="margin-top: 30px; font-size: 25px;">{{ entry.data }}</h1>


        <form method="POST" action="{{ url_for('views.add_note', entry_id=entry_id) }}" enctype="multipart/form-data">
            <textarea name="note_text" id="note_text" class="form-control" style="height: 300px;"></textarea>
            <br>
            <input type="file" name="file" id="file">
            <br>
            <div align="center">
                <button type="submit" class="btn btn-primary">Save note</button>
            </div>
        </form>

        {% if uploaded_file %}
        <div>
            <img src="{{ url_for('static', filename='css/uploads/' + uploaded_file) }}" alt="Uploaded Image">
        </div>
        {% endif %}
        
        <br>
        <hr>
        
        <br>
        <ul>
            {% for note in entry_notes %}
            <li>{{ note.content }} </li>
                <form action="{{ url_for('views.delete_note', note_id=note.id) }}" method="post" style="display: inline;">
                    <button type="submit" class="btn btn-primary" style="padding: 0px;">Delete Note</button>
                </form>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-4">
        <h1 align="center" style="margin-top: 100px;">Diary Entries</h1>
        <h1 align="center" style="margin-top: 50px; font-size: 20px;">Add today's date or a title:</h1>
        <ul class="list-group list-group-flush" id="entries">
            {% for entry in entries %}
            <li class="list-group-item">
                <a href="{{ url_for('views.entry', entry_id=entry.id) }}">{{ entry.data}}</a>
                <form action="{{ url_for('views.delete_entry', entry_id=entry.id) }}" method="post" style="display: inline;">
                    <button type="submit" class="close" aria-label="Delete">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </form>


                <ul>
                    {% for note in entry.notes %}
                    <li>{{ note.content }} 
                        <form action="{{ url_for('views.delete_note', note_id=note.id) }}" method="post" style="display: inline;">
                            <button type="submit" class="btn btn-link" style="padding: 0px;">Delete</button>
                        </form>
                    </li>
                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>


        <form method="POST">
            <textarea name="entry" id="entry" class="form-control"></textarea>
            <br />
            <div align="center">
                <button type="submit" class="btn btn-primary">Add Diary Entry</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}


{% block styles %}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock %}

{% block content %}
<main class="form-signin">
  <div class="d-flex align-items-center vh-100">
    <form method="POST" class="w-100">
      <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

      <!-- Email address -->
      <label for="email" class="mb-1">Email Address</label>
      <div class="form-floating mb-3">
        <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com">
      </div>


      <!-- Password -->
      <label for="password" class="mb-1">Password</label>
      <div class="form-floating mb-3">
        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
      </div>


      <div class="form-check text-start my-3">
        <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
        <label class="form-check-label" for="flexCheckDefault">
          Remember me
        </label>
      </div>


      <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    </form>
  </div>
</main>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %}

{% block content %}
<main class="form-signup">
    <div class="d-flex align-items-center vh-100 justify-content-center">
        <form method="POST">
            <h3 align="center" style="margin-bottom: 23px;">Sign Up</h3>
            <div class="form-group">
                <label for="email">Email Address</label> 
                <input 
                type="email" 
                class="form-control" 
                id="email" 
                name="email" 
                placeholder="Enter email"
            />
            </div>
            <div class="form-group">
                <label for="firstName">First Name</label> 
                <input 
                type="text" 
                class="form-control" 
                id="firstName" 
                name="firstName" 
                placeholder="Enter first name"
            />
            </div>
            <div class="form-group">
                <label for="password1">Password</label> 
                <input 
                type="password" 
                class="form-control" 
                id="password1" 
                name="password1" 
                placeholder="Enter password"
            />
            </div>
            <div class="form-group">
                <label for="password2">Password (Confirm)</label> 
                <input 
                type="password" 
                class="form-control" 
                id="password2" 
                name="password2" 
                placeholder="Confirm password"
            />
            </div>
            <br />
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</main>
{% endblock %}

website/templates/user.html
{% extends "base.html" %}
{% block title %}User{% endblock %}

{% block content %}
<div class="container" style="margin-top: 50px;">
    <h1 style="font-size: 25px;">Hi {{ first_name}}!</h1>

    <form action="{{ url_for('views.user') }}" method="GET">
        <input type="text" name="search_query" placeholder="Search your entries">
        <button type="submit">Search</button>
    </form>
    <br>
    <h2>All your entries:</h2>
    <ul>
        {% for entry in search_results %}
            <li><a href="{{ url_for('views.entry', entry_id=entry.id) }}">{{ entry.data }}</a></li>
        {% else %}
            <li>No results found</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}